ekf_filter_node:
  ros__parameters:
    two_d_mode: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # IMU
    imu0: "imu/data"
    imu0_config: [false, false, false, # Pose
                  false, false, true,    # Orient
                  false, false, false, # Lin Vel
                  true, true, true,    # Ang Vel
                  true, true, true]    # Lin Accel

    # Wheel encoder velocity
    odom0: "h2l_node/wheel_odometry"
    odom0_config: [true, true, false, # Pose
                    false, false, true, # Orient
                    true, false, false,  # Lin Vel
                    false, false, true,  # Ang Vel
                    false, false, false] # Lin Accel

    # pose0: "pose" #This might be in the wrong frame, don't use yet
    # pose0:_config: [true, true, false,  # Pose
    #                 false, false, true, # Orient
    #                 false, false, false, # Lin Vel
    #                 false, false, false,  # Ang Vel
    #                 false, false, false] # Lin Accel