ekf_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # IMU
    imu0: "imu/data"
    imu0_config: [false, false, false,  # Position X, Y, Z (not used)
                  true, true, true,    # Orientation (roll, pitch, yaw)
                  false, false, false, # Linear velocity (not used)
                  true, true, true,    # Angular velocity (gyro)
                  true, true, true]    # Acceleration (optional)

    # Wheel encoder velocity
    twist0: "h2l_node/wheel_velocity"
    twist0_config: [true, false, false,  # X velocity (linear), ignore Y, Z
                    false, false, false,
                    false, false, false,
                    false, false, true,  # Yaw velocity (angular)
                    false, false, false]